server:
  port: 8086
spring:
  mail.host: smtp.gmail.com
  mail.port: 587
  mail.username: javapro.social
  mail.password: JavaproIDDQD
  mail.properties.mail.smtp.auth: true
  mail.properties.mail.smtp.starttls.enable: true
  liquibase:
    enabled: false
    url: jdbc:postgresql://45.134.255.54:5432/javapro?user=javapro&password=iddqd
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://45.134.255.54:5432/javapro?user=javapro&password=iddqd
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
backup:
  localpath: /home/gitlab-runner/backup/
logs:
  localpath: /home/gitlab-runner/serverlogs/











